<?php
/**
 * MatchV5ChallengesDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Riot API
 *
 * OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - Routes Table: [`routesTable.json`](../routesTable.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. ***
 *
 * OpenAPI spec version: b7cd9f901117fa03f7c4e5f9c0a954dac569f75a
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MatchV5ChallengesDtoTest Class Doc Comment
 *
 * @category    Class
 * @description Challenges DTO
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MatchV5ChallengesDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MatchV5ChallengesDto"
     */
    public function testMatchV5ChallengesDto()
    {
    }

    /**
     * Test attribute "_12_assist_streak_count"
     */
    public function testProperty12AssistStreakCount()
    {
    }

    /**
     * Test attribute "baron_buff_gold_advantage_over_threshold"
     */
    public function testPropertyBaronBuffGoldAdvantageOverThreshold()
    {
    }

    /**
     * Test attribute "control_ward_time_coverage_in_river_or_enemy_half"
     */
    public function testPropertyControlWardTimeCoverageInRiverOrEnemyHalf()
    {
    }

    /**
     * Test attribute "earliest_baron"
     */
    public function testPropertyEarliestBaron()
    {
    }

    /**
     * Test attribute "earliest_dragon_takedown"
     */
    public function testPropertyEarliestDragonTakedown()
    {
    }

    /**
     * Test attribute "earliest_elder_dragon"
     */
    public function testPropertyEarliestElderDragon()
    {
    }

    /**
     * Test attribute "early_laning_phase_gold_exp_advantage"
     */
    public function testPropertyEarlyLaningPhaseGoldExpAdvantage()
    {
    }

    /**
     * Test attribute "faster_support_quest_completion"
     */
    public function testPropertyFasterSupportQuestCompletion()
    {
    }

    /**
     * Test attribute "fastest_legendary"
     */
    public function testPropertyFastestLegendary()
    {
    }

    /**
     * Test attribute "had_afk_teammate"
     */
    public function testPropertyHadAfkTeammate()
    {
    }

    /**
     * Test attribute "highest_champion_damage"
     */
    public function testPropertyHighestChampionDamage()
    {
    }

    /**
     * Test attribute "highest_crowd_control_score"
     */
    public function testPropertyHighestCrowdControlScore()
    {
    }

    /**
     * Test attribute "highest_ward_kills"
     */
    public function testPropertyHighestWardKills()
    {
    }

    /**
     * Test attribute "jungler_kills_early_jungle"
     */
    public function testPropertyJunglerKillsEarlyJungle()
    {
    }

    /**
     * Test attribute "kills_on_laners_early_jungle_as_jungler"
     */
    public function testPropertyKillsOnLanersEarlyJungleAsJungler()
    {
    }

    /**
     * Test attribute "laning_phase_gold_exp_advantage"
     */
    public function testPropertyLaningPhaseGoldExpAdvantage()
    {
    }

    /**
     * Test attribute "legendary_count"
     */
    public function testPropertyLegendaryCount()
    {
    }

    /**
     * Test attribute "max_cs_advantage_on_lane_opponent"
     */
    public function testPropertyMaxCsAdvantageOnLaneOpponent()
    {
    }

    /**
     * Test attribute "max_level_lead_lane_opponent"
     */
    public function testPropertyMaxLevelLeadLaneOpponent()
    {
    }

    /**
     * Test attribute "most_wards_destroyed_one_sweeper"
     */
    public function testPropertyMostWardsDestroyedOneSweeper()
    {
    }

    /**
     * Test attribute "mythic_item_used"
     */
    public function testPropertyMythicItemUsed()
    {
    }

    /**
     * Test attribute "played_champ_select_position"
     */
    public function testPropertyPlayedChampSelectPosition()
    {
    }

    /**
     * Test attribute "solo_turrets_lategame"
     */
    public function testPropertySoloTurretsLategame()
    {
    }

    /**
     * Test attribute "takedowns_first25_minutes"
     */
    public function testPropertyTakedownsFirst25Minutes()
    {
    }

    /**
     * Test attribute "teleport_takedowns"
     */
    public function testPropertyTeleportTakedowns()
    {
    }

    /**
     * Test attribute "third_inhibitor_destroyed_time"
     */
    public function testPropertyThirdInhibitorDestroyedTime()
    {
    }

    /**
     * Test attribute "three_wards_one_sweeper_count"
     */
    public function testPropertyThreeWardsOneSweeperCount()
    {
    }

    /**
     * Test attribute "vision_score_advantage_lane_opponent"
     */
    public function testPropertyVisionScoreAdvantageLaneOpponent()
    {
    }

    /**
     * Test attribute "infernal_scale_pickup"
     */
    public function testPropertyInfernalScalePickup()
    {
    }

    /**
     * Test attribute "fist_bump_participation"
     */
    public function testPropertyFistBumpParticipation()
    {
    }

    /**
     * Test attribute "void_monster_kill"
     */
    public function testPropertyVoidMonsterKill()
    {
    }

    /**
     * Test attribute "ability_uses"
     */
    public function testPropertyAbilityUses()
    {
    }

    /**
     * Test attribute "aces_before15_minutes"
     */
    public function testPropertyAcesBefore15Minutes()
    {
    }

    /**
     * Test attribute "allied_jungle_monster_kills"
     */
    public function testPropertyAlliedJungleMonsterKills()
    {
    }

    /**
     * Test attribute "baron_takedowns"
     */
    public function testPropertyBaronTakedowns()
    {
    }

    /**
     * Test attribute "blast_cone_opposite_opponent_count"
     */
    public function testPropertyBlastConeOppositeOpponentCount()
    {
    }

    /**
     * Test attribute "bounty_gold"
     */
    public function testPropertyBountyGold()
    {
    }

    /**
     * Test attribute "buffs_stolen"
     */
    public function testPropertyBuffsStolen()
    {
    }

    /**
     * Test attribute "complete_support_quest_in_time"
     */
    public function testPropertyCompleteSupportQuestInTime()
    {
    }

    /**
     * Test attribute "control_wards_placed"
     */
    public function testPropertyControlWardsPlaced()
    {
    }

    /**
     * Test attribute "damage_per_minute"
     */
    public function testPropertyDamagePerMinute()
    {
    }

    /**
     * Test attribute "damage_taken_on_team_percentage"
     */
    public function testPropertyDamageTakenOnTeamPercentage()
    {
    }

    /**
     * Test attribute "danced_with_rift_herald"
     */
    public function testPropertyDancedWithRiftHerald()
    {
    }

    /**
     * Test attribute "deaths_by_enemy_champs"
     */
    public function testPropertyDeathsByEnemyChamps()
    {
    }

    /**
     * Test attribute "dodge_skill_shots_small_window"
     */
    public function testPropertyDodgeSkillShotsSmallWindow()
    {
    }

    /**
     * Test attribute "double_aces"
     */
    public function testPropertyDoubleAces()
    {
    }

    /**
     * Test attribute "dragon_takedowns"
     */
    public function testPropertyDragonTakedowns()
    {
    }

    /**
     * Test attribute "legendary_item_used"
     */
    public function testPropertyLegendaryItemUsed()
    {
    }

    /**
     * Test attribute "effective_heal_and_shielding"
     */
    public function testPropertyEffectiveHealAndShielding()
    {
    }

    /**
     * Test attribute "elder_dragon_kills_with_opposing_soul"
     */
    public function testPropertyElderDragonKillsWithOpposingSoul()
    {
    }

    /**
     * Test attribute "elder_dragon_multikills"
     */
    public function testPropertyElderDragonMultikills()
    {
    }

    /**
     * Test attribute "enemy_champion_immobilizations"
     */
    public function testPropertyEnemyChampionImmobilizations()
    {
    }

    /**
     * Test attribute "enemy_jungle_monster_kills"
     */
    public function testPropertyEnemyJungleMonsterKills()
    {
    }

    /**
     * Test attribute "epic_monster_kills_near_enemy_jungler"
     */
    public function testPropertyEpicMonsterKillsNearEnemyJungler()
    {
    }

    /**
     * Test attribute "epic_monster_kills_within30_seconds_of_spawn"
     */
    public function testPropertyEpicMonsterKillsWithin30SecondsOfSpawn()
    {
    }

    /**
     * Test attribute "epic_monster_steals"
     */
    public function testPropertyEpicMonsterSteals()
    {
    }

    /**
     * Test attribute "epic_monster_stolen_without_smite"
     */
    public function testPropertyEpicMonsterStolenWithoutSmite()
    {
    }

    /**
     * Test attribute "first_turret_killed"
     */
    public function testPropertyFirstTurretKilled()
    {
    }

    /**
     * Test attribute "first_turret_killed_time"
     */
    public function testPropertyFirstTurretKilledTime()
    {
    }

    /**
     * Test attribute "flawless_aces"
     */
    public function testPropertyFlawlessAces()
    {
    }

    /**
     * Test attribute "full_team_takedown"
     */
    public function testPropertyFullTeamTakedown()
    {
    }

    /**
     * Test attribute "game_length"
     */
    public function testPropertyGameLength()
    {
    }

    /**
     * Test attribute "get_takedowns_in_all_lanes_early_jungle_as_laner"
     */
    public function testPropertyGetTakedownsInAllLanesEarlyJungleAsLaner()
    {
    }

    /**
     * Test attribute "gold_per_minute"
     */
    public function testPropertyGoldPerMinute()
    {
    }

    /**
     * Test attribute "had_open_nexus"
     */
    public function testPropertyHadOpenNexus()
    {
    }

    /**
     * Test attribute "immobilize_and_kill_with_ally"
     */
    public function testPropertyImmobilizeAndKillWithAlly()
    {
    }

    /**
     * Test attribute "initial_buff_count"
     */
    public function testPropertyInitialBuffCount()
    {
    }

    /**
     * Test attribute "initial_crab_count"
     */
    public function testPropertyInitialCrabCount()
    {
    }

    /**
     * Test attribute "jungle_cs_before10_minutes"
     */
    public function testPropertyJungleCsBefore10Minutes()
    {
    }

    /**
     * Test attribute "jungler_takedowns_near_damaged_epic_monster"
     */
    public function testPropertyJunglerTakedownsNearDamagedEpicMonster()
    {
    }

    /**
     * Test attribute "kda"
     */
    public function testPropertyKda()
    {
    }

    /**
     * Test attribute "kill_after_hidden_with_ally"
     */
    public function testPropertyKillAfterHiddenWithAlly()
    {
    }

    /**
     * Test attribute "killed_champ_took_full_team_damage_survived"
     */
    public function testPropertyKilledChampTookFullTeamDamageSurvived()
    {
    }

    /**
     * Test attribute "killing_sprees"
     */
    public function testPropertyKillingSprees()
    {
    }

    /**
     * Test attribute "kill_participation"
     */
    public function testPropertyKillParticipation()
    {
    }

    /**
     * Test attribute "kills_near_enemy_turret"
     */
    public function testPropertyKillsNearEnemyTurret()
    {
    }

    /**
     * Test attribute "kills_on_other_lanes_early_jungle_as_laner"
     */
    public function testPropertyKillsOnOtherLanesEarlyJungleAsLaner()
    {
    }

    /**
     * Test attribute "kills_on_recently_healed_by_aram_pack"
     */
    public function testPropertyKillsOnRecentlyHealedByAramPack()
    {
    }

    /**
     * Test attribute "kills_under_own_turret"
     */
    public function testPropertyKillsUnderOwnTurret()
    {
    }

    /**
     * Test attribute "kills_with_help_from_epic_monster"
     */
    public function testPropertyKillsWithHelpFromEpicMonster()
    {
    }

    /**
     * Test attribute "knock_enemy_into_team_and_kill"
     */
    public function testPropertyKnockEnemyIntoTeamAndKill()
    {
    }

    /**
     * Test attribute "k_turrets_destroyed_before_plates_fall"
     */
    public function testPropertyKTurretsDestroyedBeforePlatesFall()
    {
    }

    /**
     * Test attribute "land_skill_shots_early_game"
     */
    public function testPropertyLandSkillShotsEarlyGame()
    {
    }

    /**
     * Test attribute "lane_minions_first10_minutes"
     */
    public function testPropertyLaneMinionsFirst10Minutes()
    {
    }

    /**
     * Test attribute "lost_an_inhibitor"
     */
    public function testPropertyLostAnInhibitor()
    {
    }

    /**
     * Test attribute "max_kill_deficit"
     */
    public function testPropertyMaxKillDeficit()
    {
    }

    /**
     * Test attribute "mejais_full_stack_in_time"
     */
    public function testPropertyMejaisFullStackInTime()
    {
    }

    /**
     * Test attribute "more_enemy_jungle_than_opponent"
     */
    public function testPropertyMoreEnemyJungleThanOpponent()
    {
    }

    /**
     * Test attribute "multi_kill_one_spell"
     */
    public function testPropertyMultiKillOneSpell()
    {
    }

    /**
     * Test attribute "multikills"
     */
    public function testPropertyMultikills()
    {
    }

    /**
     * Test attribute "multikills_after_aggressive_flash"
     */
    public function testPropertyMultikillsAfterAggressiveFlash()
    {
    }

    /**
     * Test attribute "multi_turret_rift_herald_count"
     */
    public function testPropertyMultiTurretRiftHeraldCount()
    {
    }

    /**
     * Test attribute "outer_turret_executes_before10_minutes"
     */
    public function testPropertyOuterTurretExecutesBefore10Minutes()
    {
    }

    /**
     * Test attribute "outnumbered_kills"
     */
    public function testPropertyOutnumberedKills()
    {
    }

    /**
     * Test attribute "outnumbered_nexus_kill"
     */
    public function testPropertyOutnumberedNexusKill()
    {
    }

    /**
     * Test attribute "perfect_dragon_souls_taken"
     */
    public function testPropertyPerfectDragonSoulsTaken()
    {
    }

    /**
     * Test attribute "perfect_game"
     */
    public function testPropertyPerfectGame()
    {
    }

    /**
     * Test attribute "pick_kill_with_ally"
     */
    public function testPropertyPickKillWithAlly()
    {
    }

    /**
     * Test attribute "poro_explosions"
     */
    public function testPropertyPoroExplosions()
    {
    }

    /**
     * Test attribute "quick_cleanse"
     */
    public function testPropertyQuickCleanse()
    {
    }

    /**
     * Test attribute "quick_first_turret"
     */
    public function testPropertyQuickFirstTurret()
    {
    }

    /**
     * Test attribute "quick_solo_kills"
     */
    public function testPropertyQuickSoloKills()
    {
    }

    /**
     * Test attribute "rift_herald_takedowns"
     */
    public function testPropertyRiftHeraldTakedowns()
    {
    }

    /**
     * Test attribute "save_ally_from_death"
     */
    public function testPropertySaveAllyFromDeath()
    {
    }

    /**
     * Test attribute "scuttle_crab_kills"
     */
    public function testPropertyScuttleCrabKills()
    {
    }

    /**
     * Test attribute "shortest_time_to_ace_from_first_takedown"
     */
    public function testPropertyShortestTimeToAceFromFirstTakedown()
    {
    }

    /**
     * Test attribute "skillshots_dodged"
     */
    public function testPropertySkillshotsDodged()
    {
    }

    /**
     * Test attribute "skillshots_hit"
     */
    public function testPropertySkillshotsHit()
    {
    }

    /**
     * Test attribute "snowballs_hit"
     */
    public function testPropertySnowballsHit()
    {
    }

    /**
     * Test attribute "solo_baron_kills"
     */
    public function testPropertySoloBaronKills()
    {
    }

    /**
     * Test attribute "swarm_defeat_aatrox"
     */
    public function testPropertySwarmDefeatAatrox()
    {
    }

    /**
     * Test attribute "swarm_defeat_briar"
     */
    public function testPropertySwarmDefeatBriar()
    {
    }

    /**
     * Test attribute "swarm_defeat_mini_bosses"
     */
    public function testPropertySwarmDefeatMiniBosses()
    {
    }

    /**
     * Test attribute "swarm_evolve_weapon"
     */
    public function testPropertySwarmEvolveWeapon()
    {
    }

    /**
     * Test attribute "swarm_have3_passives"
     */
    public function testPropertySwarmHave3Passives()
    {
    }

    /**
     * Test attribute "swarm_kill_enemy"
     */
    public function testPropertySwarmKillEnemy()
    {
    }

    /**
     * Test attribute "swarm_pickup_gold"
     */
    public function testPropertySwarmPickupGold()
    {
    }

    /**
     * Test attribute "swarm_reach_level50"
     */
    public function testPropertySwarmReachLevel50()
    {
    }

    /**
     * Test attribute "swarm_survive15_min"
     */
    public function testPropertySwarmSurvive15Min()
    {
    }

    /**
     * Test attribute "swarm_win_with5_evolved_weapons"
     */
    public function testPropertySwarmWinWith5EvolvedWeapons()
    {
    }

    /**
     * Test attribute "solo_kills"
     */
    public function testPropertySoloKills()
    {
    }

    /**
     * Test attribute "stealth_wards_placed"
     */
    public function testPropertyStealthWardsPlaced()
    {
    }

    /**
     * Test attribute "survived_single_digit_hp_count"
     */
    public function testPropertySurvivedSingleDigitHpCount()
    {
    }

    /**
     * Test attribute "survived_three_immobilizes_in_fight"
     */
    public function testPropertySurvivedThreeImmobilizesInFight()
    {
    }

    /**
     * Test attribute "takedown_on_first_turret"
     */
    public function testPropertyTakedownOnFirstTurret()
    {
    }

    /**
     * Test attribute "takedowns"
     */
    public function testPropertyTakedowns()
    {
    }

    /**
     * Test attribute "takedowns_after_gaining_level_advantage"
     */
    public function testPropertyTakedownsAfterGainingLevelAdvantage()
    {
    }

    /**
     * Test attribute "takedowns_before_jungle_minion_spawn"
     */
    public function testPropertyTakedownsBeforeJungleMinionSpawn()
    {
    }

    /**
     * Test attribute "takedowns_first_x_minutes"
     */
    public function testPropertyTakedownsFirstXMinutes()
    {
    }

    /**
     * Test attribute "takedowns_in_alcove"
     */
    public function testPropertyTakedownsInAlcove()
    {
    }

    /**
     * Test attribute "takedowns_in_enemy_fountain"
     */
    public function testPropertyTakedownsInEnemyFountain()
    {
    }

    /**
     * Test attribute "team_baron_kills"
     */
    public function testPropertyTeamBaronKills()
    {
    }

    /**
     * Test attribute "team_damage_percentage"
     */
    public function testPropertyTeamDamagePercentage()
    {
    }

    /**
     * Test attribute "team_elder_dragon_kills"
     */
    public function testPropertyTeamElderDragonKills()
    {
    }

    /**
     * Test attribute "team_rift_herald_kills"
     */
    public function testPropertyTeamRiftHeraldKills()
    {
    }

    /**
     * Test attribute "took_large_damage_survived"
     */
    public function testPropertyTookLargeDamageSurvived()
    {
    }

    /**
     * Test attribute "turret_plates_taken"
     */
    public function testPropertyTurretPlatesTaken()
    {
    }

    /**
     * Test attribute "turrets_taken_with_rift_herald"
     */
    public function testPropertyTurretsTakenWithRiftHerald()
    {
    }

    /**
     * Test attribute "turret_takedowns"
     */
    public function testPropertyTurretTakedowns()
    {
    }

    /**
     * Test attribute "twenty_minions_in3_seconds_count"
     */
    public function testPropertyTwentyMinionsIn3SecondsCount()
    {
    }

    /**
     * Test attribute "two_wards_one_sweeper_count"
     */
    public function testPropertyTwoWardsOneSweeperCount()
    {
    }

    /**
     * Test attribute "unseen_recalls"
     */
    public function testPropertyUnseenRecalls()
    {
    }

    /**
     * Test attribute "vision_score_per_minute"
     */
    public function testPropertyVisionScorePerMinute()
    {
    }

    /**
     * Test attribute "wards_guarded"
     */
    public function testPropertyWardsGuarded()
    {
    }

    /**
     * Test attribute "ward_takedowns"
     */
    public function testPropertyWardTakedowns()
    {
    }

    /**
     * Test attribute "ward_takedowns_before20_m"
     */
    public function testPropertyWardTakedownsBefore20M()
    {
    }
}
