<?php
/**
 * MatchV5ParticipantDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Riot API
 *
 * OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - Routes Table: [`routesTable.json`](../routesTable.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. ***
 *
 * OpenAPI spec version: b7cd9f901117fa03f7c4e5f9c0a954dac569f75a
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MatchV5ParticipantDtoTest Class Doc Comment
 *
 * @category    Class
 * @description MatchV5ParticipantDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MatchV5ParticipantDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MatchV5ParticipantDto"
     */
    public function testMatchV5ParticipantDto()
    {
    }

    /**
     * Test attribute "all_in_pings"
     */
    public function testPropertyAllInPings()
    {
    }

    /**
     * Test attribute "assist_me_pings"
     */
    public function testPropertyAssistMePings()
    {
    }

    /**
     * Test attribute "assists"
     */
    public function testPropertyAssists()
    {
    }

    /**
     * Test attribute "baron_kills"
     */
    public function testPropertyBaronKills()
    {
    }

    /**
     * Test attribute "bounty_level"
     */
    public function testPropertyBountyLevel()
    {
    }

    /**
     * Test attribute "champ_experience"
     */
    public function testPropertyChampExperience()
    {
    }

    /**
     * Test attribute "champ_level"
     */
    public function testPropertyChampLevel()
    {
    }

    /**
     * Test attribute "champion_id"
     */
    public function testPropertyChampionId()
    {
    }

    /**
     * Test attribute "champion_name"
     */
    public function testPropertyChampionName()
    {
    }

    /**
     * Test attribute "command_pings"
     */
    public function testPropertyCommandPings()
    {
    }

    /**
     * Test attribute "champion_transform"
     */
    public function testPropertyChampionTransform()
    {
    }

    /**
     * Test attribute "consumables_purchased"
     */
    public function testPropertyConsumablesPurchased()
    {
    }

    /**
     * Test attribute "challenges"
     */
    public function testPropertyChallenges()
    {
    }

    /**
     * Test attribute "damage_dealt_to_buildings"
     */
    public function testPropertyDamageDealtToBuildings()
    {
    }

    /**
     * Test attribute "damage_dealt_to_objectives"
     */
    public function testPropertyDamageDealtToObjectives()
    {
    }

    /**
     * Test attribute "damage_dealt_to_turrets"
     */
    public function testPropertyDamageDealtToTurrets()
    {
    }

    /**
     * Test attribute "damage_self_mitigated"
     */
    public function testPropertyDamageSelfMitigated()
    {
    }

    /**
     * Test attribute "deaths"
     */
    public function testPropertyDeaths()
    {
    }

    /**
     * Test attribute "detector_wards_placed"
     */
    public function testPropertyDetectorWardsPlaced()
    {
    }

    /**
     * Test attribute "double_kills"
     */
    public function testPropertyDoubleKills()
    {
    }

    /**
     * Test attribute "dragon_kills"
     */
    public function testPropertyDragonKills()
    {
    }

    /**
     * Test attribute "eligible_for_progression"
     */
    public function testPropertyEligibleForProgression()
    {
    }

    /**
     * Test attribute "enemy_missing_pings"
     */
    public function testPropertyEnemyMissingPings()
    {
    }

    /**
     * Test attribute "enemy_vision_pings"
     */
    public function testPropertyEnemyVisionPings()
    {
    }

    /**
     * Test attribute "first_blood_assist"
     */
    public function testPropertyFirstBloodAssist()
    {
    }

    /**
     * Test attribute "first_blood_kill"
     */
    public function testPropertyFirstBloodKill()
    {
    }

    /**
     * Test attribute "first_tower_assist"
     */
    public function testPropertyFirstTowerAssist()
    {
    }

    /**
     * Test attribute "first_tower_kill"
     */
    public function testPropertyFirstTowerKill()
    {
    }

    /**
     * Test attribute "game_ended_in_early_surrender"
     */
    public function testPropertyGameEndedInEarlySurrender()
    {
    }

    /**
     * Test attribute "game_ended_in_surrender"
     */
    public function testPropertyGameEndedInSurrender()
    {
    }

    /**
     * Test attribute "hold_pings"
     */
    public function testPropertyHoldPings()
    {
    }

    /**
     * Test attribute "get_back_pings"
     */
    public function testPropertyGetBackPings()
    {
    }

    /**
     * Test attribute "gold_earned"
     */
    public function testPropertyGoldEarned()
    {
    }

    /**
     * Test attribute "gold_spent"
     */
    public function testPropertyGoldSpent()
    {
    }

    /**
     * Test attribute "individual_position"
     */
    public function testPropertyIndividualPosition()
    {
    }

    /**
     * Test attribute "inhibitor_kills"
     */
    public function testPropertyInhibitorKills()
    {
    }

    /**
     * Test attribute "inhibitor_takedowns"
     */
    public function testPropertyInhibitorTakedowns()
    {
    }

    /**
     * Test attribute "inhibitors_lost"
     */
    public function testPropertyInhibitorsLost()
    {
    }

    /**
     * Test attribute "item0"
     */
    public function testPropertyItem0()
    {
    }

    /**
     * Test attribute "item1"
     */
    public function testPropertyItem1()
    {
    }

    /**
     * Test attribute "item2"
     */
    public function testPropertyItem2()
    {
    }

    /**
     * Test attribute "item3"
     */
    public function testPropertyItem3()
    {
    }

    /**
     * Test attribute "item4"
     */
    public function testPropertyItem4()
    {
    }

    /**
     * Test attribute "item5"
     */
    public function testPropertyItem5()
    {
    }

    /**
     * Test attribute "item6"
     */
    public function testPropertyItem6()
    {
    }

    /**
     * Test attribute "items_purchased"
     */
    public function testPropertyItemsPurchased()
    {
    }

    /**
     * Test attribute "killing_sprees"
     */
    public function testPropertyKillingSprees()
    {
    }

    /**
     * Test attribute "kills"
     */
    public function testPropertyKills()
    {
    }

    /**
     * Test attribute "lane"
     */
    public function testPropertyLane()
    {
    }

    /**
     * Test attribute "largest_critical_strike"
     */
    public function testPropertyLargestCriticalStrike()
    {
    }

    /**
     * Test attribute "largest_killing_spree"
     */
    public function testPropertyLargestKillingSpree()
    {
    }

    /**
     * Test attribute "largest_multi_kill"
     */
    public function testPropertyLargestMultiKill()
    {
    }

    /**
     * Test attribute "longest_time_spent_living"
     */
    public function testPropertyLongestTimeSpentLiving()
    {
    }

    /**
     * Test attribute "magic_damage_dealt"
     */
    public function testPropertyMagicDamageDealt()
    {
    }

    /**
     * Test attribute "magic_damage_dealt_to_champions"
     */
    public function testPropertyMagicDamageDealtToChampions()
    {
    }

    /**
     * Test attribute "magic_damage_taken"
     */
    public function testPropertyMagicDamageTaken()
    {
    }

    /**
     * Test attribute "missions"
     */
    public function testPropertyMissions()
    {
    }

    /**
     * Test attribute "neutral_minions_killed"
     */
    public function testPropertyNeutralMinionsKilled()
    {
    }

    /**
     * Test attribute "need_vision_pings"
     */
    public function testPropertyNeedVisionPings()
    {
    }

    /**
     * Test attribute "nexus_kills"
     */
    public function testPropertyNexusKills()
    {
    }

    /**
     * Test attribute "nexus_takedowns"
     */
    public function testPropertyNexusTakedowns()
    {
    }

    /**
     * Test attribute "nexus_lost"
     */
    public function testPropertyNexusLost()
    {
    }

    /**
     * Test attribute "objectives_stolen"
     */
    public function testPropertyObjectivesStolen()
    {
    }

    /**
     * Test attribute "objectives_stolen_assists"
     */
    public function testPropertyObjectivesStolenAssists()
    {
    }

    /**
     * Test attribute "on_my_way_pings"
     */
    public function testPropertyOnMyWayPings()
    {
    }

    /**
     * Test attribute "participant_id"
     */
    public function testPropertyParticipantId()
    {
    }

    /**
     * Test attribute "player_score0"
     */
    public function testPropertyPlayerScore0()
    {
    }

    /**
     * Test attribute "player_score1"
     */
    public function testPropertyPlayerScore1()
    {
    }

    /**
     * Test attribute "player_score2"
     */
    public function testPropertyPlayerScore2()
    {
    }

    /**
     * Test attribute "player_score3"
     */
    public function testPropertyPlayerScore3()
    {
    }

    /**
     * Test attribute "player_score4"
     */
    public function testPropertyPlayerScore4()
    {
    }

    /**
     * Test attribute "player_score5"
     */
    public function testPropertyPlayerScore5()
    {
    }

    /**
     * Test attribute "player_score6"
     */
    public function testPropertyPlayerScore6()
    {
    }

    /**
     * Test attribute "player_score7"
     */
    public function testPropertyPlayerScore7()
    {
    }

    /**
     * Test attribute "player_score8"
     */
    public function testPropertyPlayerScore8()
    {
    }

    /**
     * Test attribute "player_score9"
     */
    public function testPropertyPlayerScore9()
    {
    }

    /**
     * Test attribute "player_score10"
     */
    public function testPropertyPlayerScore10()
    {
    }

    /**
     * Test attribute "player_score11"
     */
    public function testPropertyPlayerScore11()
    {
    }

    /**
     * Test attribute "penta_kills"
     */
    public function testPropertyPentaKills()
    {
    }

    /**
     * Test attribute "perks"
     */
    public function testPropertyPerks()
    {
    }

    /**
     * Test attribute "physical_damage_dealt"
     */
    public function testPropertyPhysicalDamageDealt()
    {
    }

    /**
     * Test attribute "physical_damage_dealt_to_champions"
     */
    public function testPropertyPhysicalDamageDealtToChampions()
    {
    }

    /**
     * Test attribute "physical_damage_taken"
     */
    public function testPropertyPhysicalDamageTaken()
    {
    }

    /**
     * Test attribute "placement"
     */
    public function testPropertyPlacement()
    {
    }

    /**
     * Test attribute "player_augment1"
     */
    public function testPropertyPlayerAugment1()
    {
    }

    /**
     * Test attribute "player_augment2"
     */
    public function testPropertyPlayerAugment2()
    {
    }

    /**
     * Test attribute "player_augment3"
     */
    public function testPropertyPlayerAugment3()
    {
    }

    /**
     * Test attribute "player_augment4"
     */
    public function testPropertyPlayerAugment4()
    {
    }

    /**
     * Test attribute "player_subteam_id"
     */
    public function testPropertyPlayerSubteamId()
    {
    }

    /**
     * Test attribute "push_pings"
     */
    public function testPropertyPushPings()
    {
    }

    /**
     * Test attribute "profile_icon"
     */
    public function testPropertyProfileIcon()
    {
    }

    /**
     * Test attribute "puuid"
     */
    public function testPropertyPuuid()
    {
    }

    /**
     * Test attribute "quadra_kills"
     */
    public function testPropertyQuadraKills()
    {
    }

    /**
     * Test attribute "riot_id_game_name"
     */
    public function testPropertyRiotIdGameName()
    {
    }

    /**
     * Test attribute "riot_id_name"
     */
    public function testPropertyRiotIdName()
    {
    }

    /**
     * Test attribute "riot_id_tagline"
     */
    public function testPropertyRiotIdTagline()
    {
    }

    /**
     * Test attribute "role"
     */
    public function testPropertyRole()
    {
    }

    /**
     * Test attribute "sight_wards_bought_in_game"
     */
    public function testPropertySightWardsBoughtInGame()
    {
    }

    /**
     * Test attribute "spell1_casts"
     */
    public function testPropertySpell1Casts()
    {
    }

    /**
     * Test attribute "spell2_casts"
     */
    public function testPropertySpell2Casts()
    {
    }

    /**
     * Test attribute "spell3_casts"
     */
    public function testPropertySpell3Casts()
    {
    }

    /**
     * Test attribute "spell4_casts"
     */
    public function testPropertySpell4Casts()
    {
    }

    /**
     * Test attribute "subteam_placement"
     */
    public function testPropertySubteamPlacement()
    {
    }

    /**
     * Test attribute "summoner1_casts"
     */
    public function testPropertySummoner1Casts()
    {
    }

    /**
     * Test attribute "summoner1_id"
     */
    public function testPropertySummoner1Id()
    {
    }

    /**
     * Test attribute "summoner2_casts"
     */
    public function testPropertySummoner2Casts()
    {
    }

    /**
     * Test attribute "summoner2_id"
     */
    public function testPropertySummoner2Id()
    {
    }

    /**
     * Test attribute "summoner_id"
     */
    public function testPropertySummonerId()
    {
    }

    /**
     * Test attribute "summoner_level"
     */
    public function testPropertySummonerLevel()
    {
    }

    /**
     * Test attribute "summoner_name"
     */
    public function testPropertySummonerName()
    {
    }

    /**
     * Test attribute "team_early_surrendered"
     */
    public function testPropertyTeamEarlySurrendered()
    {
    }

    /**
     * Test attribute "team_id"
     */
    public function testPropertyTeamId()
    {
    }

    /**
     * Test attribute "team_position"
     */
    public function testPropertyTeamPosition()
    {
    }

    /**
     * Test attribute "time_c_cing_others"
     */
    public function testPropertyTimeCCingOthers()
    {
    }

    /**
     * Test attribute "time_played"
     */
    public function testPropertyTimePlayed()
    {
    }

    /**
     * Test attribute "total_ally_jungle_minions_killed"
     */
    public function testPropertyTotalAllyJungleMinionsKilled()
    {
    }

    /**
     * Test attribute "total_damage_dealt"
     */
    public function testPropertyTotalDamageDealt()
    {
    }

    /**
     * Test attribute "total_damage_dealt_to_champions"
     */
    public function testPropertyTotalDamageDealtToChampions()
    {
    }

    /**
     * Test attribute "total_damage_shielded_on_teammates"
     */
    public function testPropertyTotalDamageShieldedOnTeammates()
    {
    }

    /**
     * Test attribute "total_damage_taken"
     */
    public function testPropertyTotalDamageTaken()
    {
    }

    /**
     * Test attribute "total_enemy_jungle_minions_killed"
     */
    public function testPropertyTotalEnemyJungleMinionsKilled()
    {
    }

    /**
     * Test attribute "total_heal"
     */
    public function testPropertyTotalHeal()
    {
    }

    /**
     * Test attribute "total_heals_on_teammates"
     */
    public function testPropertyTotalHealsOnTeammates()
    {
    }

    /**
     * Test attribute "total_minions_killed"
     */
    public function testPropertyTotalMinionsKilled()
    {
    }

    /**
     * Test attribute "total_time_cc_dealt"
     */
    public function testPropertyTotalTimeCcDealt()
    {
    }

    /**
     * Test attribute "total_time_spent_dead"
     */
    public function testPropertyTotalTimeSpentDead()
    {
    }

    /**
     * Test attribute "total_units_healed"
     */
    public function testPropertyTotalUnitsHealed()
    {
    }

    /**
     * Test attribute "triple_kills"
     */
    public function testPropertyTripleKills()
    {
    }

    /**
     * Test attribute "true_damage_dealt"
     */
    public function testPropertyTrueDamageDealt()
    {
    }

    /**
     * Test attribute "true_damage_dealt_to_champions"
     */
    public function testPropertyTrueDamageDealtToChampions()
    {
    }

    /**
     * Test attribute "true_damage_taken"
     */
    public function testPropertyTrueDamageTaken()
    {
    }

    /**
     * Test attribute "turret_kills"
     */
    public function testPropertyTurretKills()
    {
    }

    /**
     * Test attribute "turret_takedowns"
     */
    public function testPropertyTurretTakedowns()
    {
    }

    /**
     * Test attribute "turrets_lost"
     */
    public function testPropertyTurretsLost()
    {
    }

    /**
     * Test attribute "unreal_kills"
     */
    public function testPropertyUnrealKills()
    {
    }

    /**
     * Test attribute "vision_score"
     */
    public function testPropertyVisionScore()
    {
    }

    /**
     * Test attribute "vision_cleared_pings"
     */
    public function testPropertyVisionClearedPings()
    {
    }

    /**
     * Test attribute "vision_wards_bought_in_game"
     */
    public function testPropertyVisionWardsBoughtInGame()
    {
    }

    /**
     * Test attribute "wards_killed"
     */
    public function testPropertyWardsKilled()
    {
    }

    /**
     * Test attribute "wards_placed"
     */
    public function testPropertyWardsPlaced()
    {
    }

    /**
     * Test attribute "win"
     */
    public function testPropertyWin()
    {
    }

    /**
     * Test attribute "bait_pings"
     */
    public function testPropertyBaitPings()
    {
    }

    /**
     * Test attribute "danger_pings"
     */
    public function testPropertyDangerPings()
    {
    }

    /**
     * Test attribute "basic_pings"
     */
    public function testPropertyBasicPings()
    {
    }

    /**
     * Test attribute "player_augment5"
     */
    public function testPropertyPlayerAugment5()
    {
    }

    /**
     * Test attribute "player_augment6"
     */
    public function testPropertyPlayerAugment6()
    {
    }
}
