<?php
/**
 * TftMatchV1ParticipantDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Riot API
 *
 * OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - Routes Table: [`routesTable.json`](../routesTable.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. ***
 *
 * OpenAPI spec version: b7cd9f901117fa03f7c4e5f9c0a954dac569f75a
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TftMatchV1ParticipantDtoTest Class Doc Comment
 *
 * @category    Class
 * @description TftMatchV1ParticipantDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TftMatchV1ParticipantDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TftMatchV1ParticipantDto"
     */
    public function testTftMatchV1ParticipantDto()
    {
    }

    /**
     * Test attribute "companion"
     */
    public function testPropertyCompanion()
    {
    }

    /**
     * Test attribute "gold_left"
     */
    public function testPropertyGoldLeft()
    {
    }

    /**
     * Test attribute "last_round"
     */
    public function testPropertyLastRound()
    {
    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {
    }

    /**
     * Test attribute "placement"
     */
    public function testPropertyPlacement()
    {
    }

    /**
     * Test attribute "players_eliminated"
     */
    public function testPropertyPlayersEliminated()
    {
    }

    /**
     * Test attribute "puuid"
     */
    public function testPropertyPuuid()
    {
    }

    /**
     * Test attribute "time_eliminated"
     */
    public function testPropertyTimeEliminated()
    {
    }

    /**
     * Test attribute "total_damage_to_players"
     */
    public function testPropertyTotalDamageToPlayers()
    {
    }

    /**
     * Test attribute "traits"
     */
    public function testPropertyTraits()
    {
    }

    /**
     * Test attribute "units"
     */
    public function testPropertyUnits()
    {
    }

    /**
     * Test attribute "augments"
     */
    public function testPropertyAugments()
    {
    }

    /**
     * Test attribute "partner_group_id"
     */
    public function testPropertyPartnerGroupId()
    {
    }

    /**
     * Test attribute "missions"
     */
    public function testPropertyMissions()
    {
    }
}
